apiVersion: keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: comfyui-http
  namespace: default
spec:
  host: comfyui.weareluca.ai # external host
  targetPendingRequests: 100  # threshold before scaling out more
  scaleTargetRef:
    name: comfyui
    kind: Deployment
    port: 8848
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 10 # 10 seconds
  cooldownPeriod:  900 # 15 mins
