apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: comfyui-http-scaledobject
  namespace: default
spec:
  hosts:
    - comfyui.weareluca.ai # external host
  targetPendingRequests: 100  # threshold before scaling out more
  scaleTargetRef:
    name: comfyui
    kind: Deployment
    service: comfyui-service
    port: 8848
  replicas:
    min: 0
    max: 2
  scaledownPeriod: 900 # 15 mins
  scalingMetric:
    requestRate:
      granularity: 1s
      targetValue: 100
      window: 1m